openapi: 3.0.0
info:
  title: Last.fm Artist API
  description: API zum Abrufen von K端nstler-Infos von Last.fm
  version: 1.0.0

paths:
  /api/artist/{name}:
    get:
      summary: Holt Infos zu einem K端nstler von Last.fm
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: Name des K端nstlers
      responses:
        "200":
          description: Erfolgreiche Antwort mit K端nstler-Infos
        "500":
          description: Fehler beim Abruf
