version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./config:/config
      - ./backend/app/shared:/app/shared  # Direktes Mapping des Ordners
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true # Stelle sicher, dass Docker die Umgebung kennt

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./backend/app/shared:/app/shared # Test
    environment:
      - NODE_ENV=development