version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/src
      - ./backend/docs:/src/docs
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/src
    environment:
      - NODE_ENV=development
