version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/src
      - ./backend/docs:/src/docs
      - shared-data:/app/shared  # Gemeinsames Volume
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/src
      - shared-data:/app/shared  # Gemeinsames Volume
    environment:
      - NODE_ENV=development

volumes:
  shared-data:
