openapi: 3.0.0
info:
  title: Last.fm Artist API
  description: API zum Abrufen von Künstler-Infos von Last.fm
  version: 1.0.0

paths:
  /api/artist/{name}:
    get:
      summary: Gibt ähnliche Künstler zurück
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: Name des Künstlers
      responses:
        "200":
          description: Erfolgreiche Antwort mit Künstler-Infos
        "500":
          description: Fehler beim Abruf
